# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kwindowsystem': '@latest'
    'frameworks/kwayland': '@latest'
    'plasma/kwin': '@same'
    'plasma/kpipewire': '@same'

Options:
  require-passing-tests-on: [ 'Linux' ]
