# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt6']
  'require':
    'frameworks/extra-cmake-modules': 'Frameworks/6.24'
    'frameworks/kwindowsystem': 'Frameworks/6.24'
    'plasma/kwayland': '@same'
    'plasma/kwin': '@same'
    'plasma/kpipewire': '@same'
    'plasma/plasma-integration': '@same'
    'third-party/wayland': 'Frameworks/6.24'

- 'on': ['Linux/Qt5']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kwindowsystem': '@latest'
    'plasma/kwayland': '@latest'
    'plasma/kwin': '@latest'
    'plasma/kpipewire': '@latest'
    'third-party/wayland': '@latest'

Options:
  require-passing-tests-on: [ 'Linux/Qt6' ]
